# Notebook Title

## Setup Python and R environment
you can ignore this section

In [2]:
%load_ext rpy2.ipython
%load_ext autoreload
%autoreload 2

%matplotlib inline  
from matplotlib import rcParams
rcParams['figure.figsize'] = (16, 100)

import warnings
from rpy2.rinterface import RRuntimeWarning
warnings.filterwarnings("ignore") # Ignore all warnings
# warnings.filterwarnings("ignore", category=RRuntimeWarning) # Show some warnings

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import display, HTML

In [2]:
%%javascript
// Disable auto-scrolling
IPython.OutputArea.prototype._should_scroll = function(lines) {
    return false;
}

In [3]:
%%R

# My commonly used R imports

require('tidyverse')

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.4.4     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.0
✔ purrr     1.0.2
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

Loading required package: tidyverse

## 👉 download your data

You can write code here to download your dataset. Or if you already have it, just leave the URL in the comments and just load it into a pandas or R (or both) dataframe.

In [6]:
import pandas as pd

df = pd.read_csv("mental-health-directory-2024.csv")  
df.head()

,name1,name2,street1,street2,city,state,zip,phone,intake1,intake2,intake1a,intake2a,service_code_info
0,SpectraCare Health Systems,Henry County Clinic,219 Dothan Road,NaN,Abbeville,AL,36310,800-951-4357,NaN,NaN,NaN,NaN,SA MH SUMH * OP * CMHC * CHLOR FLUPH HALOP PER...
1,SpectraCare Health Systems,Henry County Day Treatment,1242 U.S. Highway 431 South,NaN,Abbeville,AL,36310,800-951-4357,334-951-4357,NaN,NaN,NaN,MH SUMH * OP * CMHC * CHLOR FLUPH HALOP ARIPI ...
2,South Central Alabama MHC,Covington County Mental Health Center,19815 Bay Branch Road,NaN,Andalusia,AL,36420,334-222-2523,877-530-0002,NaN,NaN,NaN,SA MH SUMH * OP PHDT * CMHC * CHLOR FLUPH HALO...
3,South Central Alabama MHC,Montezuma Complex,205 Academy Drive,NaN,Andalusia,AL,36420,334-428-5050,877-530-0002,NaN,NaN,NaN,SA MH SUMH * PHDT RES * MSMH * CHLOR FLUPH HAL...
4,RMC Anniston,NaN,400 East 10th Street,NaN,Anniston,AL,36207,256-235-5121,256-235-5482,256-741-6484,NaN,NaN,MH * HI * IPSY * CHLOR FLUPH HALOP THIOR ARIPI...

## 👉 convert addresses --> lat/long 

See the [census-examples](https://github.com/data4news/census-examples) repository for examples. If you need help, try asking in the class slack channel. Chances are someone in the class is struggling with the same problem as you are so we might as well all learn together in the same slack channel!

In [7]:
import pandas as pd
import pgeocode
from concurrent.futures import ThreadPoolExecutor
from tqdm.notebook import tqdm

df = pd.read_csv("mental-health-directory-2024.csv")

nomi = pgeocode.Nominatim("US")

def get_lat_lon(zip_code):
    """
    Get latitude and longitude for a given ZIP code.
    """
    try:
        result = nomi.query_postal_code(zip_code)
        return result.latitude, result.longitude
    except:
        return None, None

def bulk_geocode(zip_codes):
    """
    Geocode a list of ZIP codes in parallel for speed.
    """
    with ThreadPoolExecutor() as tpe:
        results = list(tqdm(tpe.map(get_lat_lon, zip_codes), total=len(zip_codes)))
    
    return pd.DataFrame(results, columns=["latitude", "longitude"])

df[['latitude', 'longitude']] = bulk_geocode(df['zip'])

df.to_csv("mental_health_facilities_geocoded.csv", index=False)

df.head()

Requirement already satisfied: pip in /Users/somaiyah/.pyenv/versions/3.12.7/lib/python3.12/site-packages (25.0.1)

  0%|          | 0/8319 [00:00<?, ?it/s]

,name1,name2,street1,street2,city,state,zip,phone,intake1,intake2,intake1a,intake2a,service_code_info,latitude,longitude
0,SpectraCare Health Systems,Henry County Clinic,219 Dothan Road,NaN,Abbeville,AL,36310,800-951-4357,NaN,NaN,NaN,NaN,SA MH SUMH * OP * CMHC * CHLOR FLUPH HALOP PER...,31.5755,-85.2790
1,SpectraCare Health Systems,Henry County Day Treatment,1242 U.S. Highway 431 South,NaN,Abbeville,AL,36310,800-951-4357,334-951-4357,NaN,NaN,NaN,MH SUMH * OP * CMHC * CHLOR FLUPH HALOP ARIPI ...,31.5755,-85.2790
2,South Central Alabama MHC,Covington County Mental Health Center,19815 Bay Branch Road,NaN,Andalusia,AL,36420,334-222-2523,877-530-0002,NaN,NaN,NaN,SA MH SUMH * OP PHDT * CMHC * CHLOR FLUPH HALO...,31.2971,-86.4905
3,South Central Alabama MHC,Montezuma Complex,205 Academy Drive,NaN,Andalusia,AL,36420,334-428-5050,877-530-0002,NaN,NaN,NaN,SA MH SUMH * PHDT RES * MSMH * CHLOR FLUPH HAL...,31.2971,-86.4905
4,RMC Anniston,NaN,400 East 10th Street,NaN,Anniston,AL,36207,256-235-5121,256-235-5482,256-741-6484,NaN,NaN,MH * HI * IPSY * CHLOR FLUPH HALOP THIOR ARIPI...,33.6803,-85.7137

## 👉 convert lat/long to census geography codes 

(like 'GEOID', 'STATE', 'COUNTY', 'TRACT', 'BLOCK', etc...)

Same note as above, see [census-examples](https://github.com/data4news/census-examples) repository for examples or ask in the class slack channel if stuck.

In [9]:
pip install censusgeocode

Collecting censusgeocode
  Downloading censusgeocode-0.5.2-py3-none-any.whl.metadata (6.6 kB)
Requirement already satisfied: requests<3,>=2.27.0 in /Users/somaiyah/.pyenv/versions/3.12.7/lib/python3.12/site-packages (from requests[security]<3,>=2.27.0->censusgeocode) (2.32.3)
Collecting requests-toolbelt<1,>=0.9.0 (from censusgeocode)
  Downloading requests_toolbelt-0.10.1-py2.py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/somaiyah/.pyenv/versions/3.12.7/lib/python3.12/site-packages (from requests<3,>=2.27.0->requests[security]<3,>=2.27.0->censusgeocode) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /Users/somaiyah/.pyenv/versions/3.12.7/lib/python3.12/site-packages (from requests<3,>=2.27.0->requests[security]<3,>=2.27.0->censusgeocode) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/somaiyah/.pyenv/versions/3.12.7/lib/python3.12/site-packages (from requests<3,>=2.27.0->requests[security]<3,>=2.27.0->censusgeocode) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /Users/somaiyah/.pyenv/versions/3.12.7/lib/python3.12/site-packages (from requests<3,>=2.27.0->requests[security]<3,>=2.27.0->censusgeocode) (2024.8.30)
Downloading censusgeocode-0.5.2-py3-none-any.whl (9.2 kB)
Downloading requests_toolbelt-0.10.1-py2.py3-none-any.whl (54 kB)
Installing collected packages: requests-toolbelt, censusgeocode
Successfully installed censusgeocode-0.5.2 requests-toolbelt-0.10.1
Note: you may need to restart the kernel to use updated packages.

In [14]:
import pandas as pd
import requests
import time
from tqdm.notebook import tqdm

df = pd.read_csv("mental_health_facilities_geocoded.csv")


df['GEOID'] = None
df['STATE'] = None
df['COUNTY'] = None
df['TRACT'] = None
df['BLOCK'] = None

for idx, row in tqdm(df.iterrows(), total=len(df)):
    if pd.isna(row['latitude']) or pd.isna(row['longitude']):
        continue
        
    try:
        url = f"https://geocoding.geo.census.gov/geocoder/geographies/coordinates?x={row['longitude']}&y={row['latitude']}&benchmark=Public_AR_Current&vintage=Current_Current&format=json"
        
        response = requests.get(url)
        
        if response.status_code == 200:
            result = response.json()
            
            if 'result' in result and 'geographies' in result['result']:
                geographies = result['result']['geographies']
                
                if '2020 Census Blocks' in geographies and len(geographies['2020 Census Blocks']) > 0:
                    block = geographies['2020 Census Blocks'][0]
                    
                    df.at[idx, 'GEOID'] = block.get('GEOID', None)
                    df.at[idx, 'STATE'] = block.get('STATE', None)
                    df.at[idx, 'COUNTY'] = block.get('COUNTY', None)
                    df.at[idx, 'TRACT'] = block.get('TRACT', None)
                    df.at[idx, 'BLOCK'] = block.get('BLOCK', None)
        
        time.sleep(0.5)
        
    except Exception as e:
        print(f"Error processing row {idx}: {e}")


df.to_csv("mental_health_facilities_with_census.csv", index=False)

  0%|          | 0/8319 [00:00<?, ?it/s]

## 👉 Output Data

Output your dataframe containing your data and the Census connector codes (like tract, block, etc...).

In [15]:
import pandas as pd

df = pd.read_csv("mental_health_facilities_with_census.csv")  
df.head()

,name1,name2,street1,street2,city,state,zip,phone,intake1,intake2,intake1a,intake2a,service_code_info,latitude,longitude,GEOID,STATE,COUNTY,TRACT,BLOCK
0,SpectraCare Health Systems,Henry County Clinic,219 Dothan Road,NaN,Abbeville,AL,36310,800-951-4357,NaN,NaN,NaN,NaN,SA MH SUMH * OP * CMHC * CHLOR FLUPH HALOP PER...,31.5755,-85.2790,1.067030e+13,1.0,67.0,30200.0,2026.0
1,SpectraCare Health Systems,Henry County Day Treatment,1242 U.S. Highway 431 South,NaN,Abbeville,AL,36310,800-951-4357,334-951-4357,NaN,NaN,NaN,MH SUMH * OP * CMHC * CHLOR FLUPH HALOP ARIPI ...,31.5755,-85.2790,1.067030e+13,1.0,67.0,30200.0,2026.0
2,South Central Alabama MHC,Covington County Mental Health Center,19815 Bay Branch Road,NaN,Andalusia,AL,36420,334-222-2523,877-530-0002,NaN,NaN,NaN,SA MH SUMH * OP PHDT * CMHC * CHLOR FLUPH HALO...,31.2971,-86.4905,1.039962e+13,1.0,39.0,961800.0,2011.0
3,South Central Alabama MHC,Montezuma Complex,205 Academy Drive,NaN,Andalusia,AL,36420,334-428-5050,877-530-0002,NaN,NaN,NaN,SA MH SUMH * PHDT RES * MSMH * CHLOR FLUPH HAL...,31.2971,-86.4905,1.039962e+13,1.0,39.0,961800.0,2011.0
4,RMC Anniston,NaN,400 East 10th Street,NaN,Anniston,AL,36207,256-235-5121,256-235-5482,256-741-6484,NaN,NaN,MH * HI * IPSY * CHLOR FLUPH HALOP THIOR ARIPI...,33.6803,-85.7137,1.015002e+13,1.0,15.0,2002.0,1002.0